# Base configs
# baseurl: "https://photography.rampatra.com"
baseurl: "https://aaygupta.github.io/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "2after5 - Photography by Prithiv Mohan"
subtitle: "See the world through my eyes!"
author: "Prithiv Mohan"
header:
 title: "2after5"
 subtitle: "by Prithiv Mohan"
footer:
 name: "Hey there, my name is Prithiv"
 bio: "I am a professional photographer."
 github: ""
web_design: ""
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
#  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/2after5"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
#  github: "https://www.github.com/rampatra"
